## Kabbadi Hacathon - Team Data

In [28]:
# Libraries go here

from bs4 import BeautifulSoup
from selenium import webdriver
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
from pandas.io.json import json_normalize

In [ ]:
# Driver location for selenium

# driver= webdriver.Chrome("E:\\Drivers\\chromedriver.exe")

# driver.get('https://www.prokabaddi.com/schedule-fixtures-results')

In [ ]:
# Importing page data

# soup=BeautifulSoup (driver.page_source, 'lxml')

In [ ]:
# Initialize required variables

# team = []
# team_data_class = [{'date' : 'matDate'}, 
#                    {'time' : 'matTime'}, 
#                    {'status' : 'matStatus'}, 
#                    {'team' : 'si-fullName'},
#                    {'score' : 'matScore'}]

In [ ]:
# # Functions

# def get_class_data(class_name):
#     '''
#     This function recieves the class name from the UI to scrape the data and returns all span text under the class
#     input : String class_name, output: List span_data
#     '''
#     return [i.span.text for i in soup.find_all('div', class_=class_name)]

In [ ]:
# for content in team_data_class:
#     for key, value in content.items():
#         locals()[key] = get_class_data(value)
#         if key == 'team':
#             team1 = team[:int(len(team)/2)]
#             team2 = team[int(len(team)/2):]

# df_s1=pd.DataFrame({'Date': date, 'Time': time, 'Status':status,'Team 1': team1, 'Team 2': team2,'Score': score})

In [ ]:
# This has overall team_stats about all the teams season basis who was mom in the match and stuffs like that. Just copy the url and paste in browser.

# data_source = [{"season_1" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/1_season.json"},
#               {"season_2" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/2_season.json"},
#               {"season_3" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/3_season.json"},
#               {"season_4" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/4_season.json"},
#               {"season_5" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_8.json"},
#               {"season_6" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_26.json"},
#               {"season_7" : "https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_49.json"}
#               ]

In [ ]:
# team_data = [ {key : requests.get(val).json()} for i in data_source for key, val in i.items()]

In [17]:
total_points = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_102_stats.json"
successful_raids = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_21_stats.json"
raid_points = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_22_stats.json"
successful_tackles = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_23_stats.json"
tackle_points = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_103_stats.json"
avg_raid_point = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_138_stats.json"
avg_tackle_points = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_139_stats.json"
dod_raid_points = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_132_stats.json"
super_raids = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_104_stats.json"
super_tackles = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_28_stats.json"
super_10s = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_100_stats.json"
high_5s = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_101_stats.json"

# sample = json_normalize(requests.get(high_5s).json()['data'])
# sample

In [33]:
players_data = []
# for url in players_meta:
dataset = requests.get(total_points).json()['data']
for i in dataset:
    player_obj = {
                    'player_id': i.get('player_id', None),
                    'player_name': i.get('player_name', None),
                    'matches_played': i.get('match_played', None),
                    'team_name': i.get('team_full_name', None),
                    'total_points': i.get('value', None),
                    'successful_raids': None,
                    'raid_points': None,
                    'successful_tackles': None,
                    'tackle_points': None,
                    'avg_raid_point': None,
                    'avg_tackle_points': None,
                    'dod_raid_points': None,
                    'super_raids': None,
                    'super_tackles': None,
                    'super_10s': None,
                    'high_5s': None 
                }
    players_data.append(player_obj)
    
dataset = requests.get(successful_raids).json()['data']

points_meta = ['successful_raids', 
          'raid_points', 
          'successful_tackles', 
          'tackle_points', 
          'avg_raid_point', 
          'avg_tackle_points', 
          'dod_raid_points', 
          'super_raids',
          'super_tackles',
          'super_10s',
          'high_5s']
for l in points_meta:
    dataset = requests.get(locals()[l]).json()['data']
    for i in dataset:
        for j in players_data:
            if i['player_id'] == j['player_id']:
                j[l] = i['value']
            else:
                continue
        
total_player_points = json_normalize(players_data)

total_player_points.to_csv('player_data.csv', header= True)

In [36]:
total_player_points

,avg_raid_point,avg_tackle_points,dod_raid_points,high_5s,matches_played,player_id,player_name,raid_points,successful_raids,successful_tackles,super_10s,super_raids,super_tackles,tackle_points,team_name,total_points
0,10.69,0.07,136.0,NaN,104,197,Pardeep Narwal,1101.0,836.0,6.0,57.0,50.0,1.0,7.0,Patna Pirates,1108
1,7.86,0.49,164.0,NaN,120,81,Rahul Chaudhari,943.0,776.0,54.0,40.0,24.0,5.0,59.0,Tamil Thalaivas,1002
2,6.96,0.71,166.0,4.0,123,41,Deepak Niwas Hooda,856.0,698.0,79.0,31.0,20.0,8.0,87.0,Jaipur Pink Panthers,943
3,6.87,0.18,163.0,NaN,115,26,Ajay Thakur,790.0,640.0,21.0,29.0,23.0,NaN,21.0,Tamil Thalaivas,811
4,9.25,0.11,102.0,NaN,79,143,Maninder Singh,731.0,586.0,8.0,33.0,21.0,1.0,9.0,Bengal Warriors,740
5,7.55,0.44,106.0,1.0,89,326,Rohit Kumar,664.0,545.0,37.0,26.0,15.0,2.0,39.0,Bengaluru Bulls,703
6,5.09,0.39,127.0,NaN,117,94,Rishank Devadiga,595.0,467.0,44.0,10.0,25.0,2.0,46.0,U.P. Yoddha,641
7,6.10,0.55,103.0,NaN,92,58,Kashiling Adake,561.0,424.0,44.0,15.0,23.0,7.0,51.0,Bengaluru Bulls,612
8,8.03,0.45,71.0,NaN,75,318,Pawan Kumar Sehrawat,578.0,445.0,31.0,26.0,19.0,3.0,34.0,Bengaluru Bulls,612
9,5.79,0.76,33.0,NaN,91,29,Anup Kumar,527.0,421.0,61.0,13.0,17.0,8.0,69.0,Jaipur Pink Panthers,596
10,2.38,3.14,19.0,23.0,108,69,Manjeet Chhillar,224.0,179.0,324.0,2.0,5.0,15.0,339.0,Tamil Thalaivas,563
11,2.13,2.47,25.0,16.0,120,142,Sandeep Narwal,247.0,191.0,268.0,1.0,11.0,28.0,296.0,U Mumba,543
12,4.47,0.22,100.0,NaN,103,12,Jang Kun Lee,460.0,366.0,20.0,9.0,14.0,3.0,23.0,Patna Pirates,483
13,6.57,0.32,73.0,NaN,69,388,Monu Goyat,453.0,377.0,19.0,20.0,7.0,3.0,22.0,U.P. Yoddha,475
14,6.87,0.46,88.0,NaN,63,757,Sachin Tanwar,433.0,356.0,26.0,16.0,4.0,3.0,29.0,Gujarat Fortunegiants,462
15,6.63,0.35,52.0,NaN,66,320,Nitin Tomar,431.0,366.0,20.0,14.0,10.0,3.0,23.0,Puneri Paltan,454
16,10.19,0.17,59.0,NaN,42,2296,Naveen Kumar,428.0,357.0,6.0,27.0,5.0,1.0,7.0,Dabang Delhi K.C.,435
17,5.00,0.42,61.0,NaN,77,52,Jasvir Singh,380.0,295.0,25.0,7.0,7.0,7.0,32.0,Tamil Thalaivas,412
18,4.04,0.15,99.0,NaN,97,111,Sukesh Hegde,392.0,294.0,13.0,1.0,15.0,2.0,15.0,Bengal Warriors,407
19,10.05,0.15,63.0,NaN,39,2026,Siddharth Sirish Desai,392.0,312.0,6.0,19.0,16.0,NaN,6.0,Telugu Titans,398
20,3.26,1.23,57.0,3.0,92,86,Rajesh Narwal,284.0,224.0,105.0,4.0,12.0,8.0,113.0,Dabang Delhi K.C.,397
21,7.57,0.18,77.0,NaN,51,366,Vikash Kandola,386.0,302.0,9.0,15.0,12.0,NaN,9.0,Haryana Steelers,395
22,3.61,0.57,95.0,NaN,95,251,Meraj Sheykh,339.0,249.0,48.0,6.0,17.0,6.0,54.0,Dabang Delhi K.C.,393
23,4.07,0.10,68.0,NaN,94,155,Prashanth Kumar Rai,370.0,286.0,6.0,11.0,8.0,3.0,9.0,Haryana Steelers,379
24,5.11,0.28,93.0,NaN,72,106,Shrikant Jadhav,358.0,276.0,17.0,10.0,8.0,3.0,20.0,U.P. Yoddha,378
25,4.54,0.07,79.0,NaN,81,219,K. Prapanjan,363.0,284.0,6.0,10.0,7.0,NaN,6.0,Bengal Warriors,369
26,0.54,2.94,NaN,23.0,109,157,Ravinder Pahal,14.0,8.0,301.0,NaN,NaN,19.0,320.0,Dabang Delhi K.C.,334
27,1.36,1.94,22.0,4.0,118,160,Ran Singh,99.0,72.0,217.0,NaN,4.0,12.0,229.0,Tamil Thalaivas,328
28,5.18,0.16,38.0,NaN,61,36,Chandran Ranjit,316.0,255.0,8.0,6.0,9.0,2.0,10.0,Dabang Delhi K.C.,326
29,3.89,0.16,71.0,NaN,81,211,Deepak Narwal,311.0,244.0,12.0,9.0,4.0,1.0,13.0,Jaipur Pink Panthers,324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,NaN,1.00,NaN,NaN,1,201,Adinath Sakharam Gavali,NaN,NaN,1.0,NaN,NaN,NaN,1.0,U Mumba,1
366,0.00,NaN,NaN,NaN,3,193,Rohit Kumar Prajapat,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Jaipur Pink Panthers,1
367,NaN,NaN,NaN,NaN,2,199,Kazuhiro Takano,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Jaipur Pink Panthers,1
368,NaN,NaN,NaN,NaN,2,224,Inderpal Bishnoi,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Dabang Delhi K.C.,1
369,NaN,NaN,NaN,NaN,1,237,Amit Kumar,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Puneri Paltan,1
370,NaN,0.25,NaN,NaN,4,148,Sunil Subhash Lande,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Puneri Paltan,1
371,NaN,0.33,NaN,NaN,3,17,Atif Waheed,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Telugu Titans,1
372,NaN,NaN,NaN,NaN,2,74,Nithesh B R,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Bengaluru Bulls,1
373,NaN,NaN,NaN,NaN,3,509,Mohammad Taghi Paein Mahali,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Bengal Warriors,1
374,NaN,NaN,1.0,NaN,1,513,Yong Joo Ok,1.0,1.0,NaN,NaN,NaN,NaN,NaN,U Mumba,1
375,0.00,NaN,NaN,NaN,3,580,Vishnu Uthaman,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Patna Pirates,1
376,NaN,NaN,NaN,NaN,2,705,Ajvender Singh,NaN,NaN,1.0,NaN,NaN,NaN,1.0,U.P. Yoddha,1
377,NaN,0.25,NaN,NaN,4,312,Sanju,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Dabang Delhi K.C.,1
378,NaN,NaN,NaN,NaN,1,307,Ravinandan G.M.,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Dabang Delhi K.C.,1
379,NaN,NaN,NaN,NaN,1,296,Navjot Singh,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Dabang Delhi K.C.,1
380,NaN,NaN,1.0,NaN,1,315,Parvesh Attri,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Bengaluru Bulls,1
381,NaN,NaN,NaN,NaN,1,317,Hardeep Duhan,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Bengaluru Bulls,1
382,NaN,NaN,NaN,NaN,1,373,Parveen Narwal,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Jaipur Pink Panthers,1
383,NaN,1.00,NaN,NaN,1,364,Ajay Singh,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Bengaluru Bulls,1
384,NaN,NaN,1.0,NaN,1,367,Nitin Kumar,1.0,1.0,NaN,NaN,NaN,NaN,NaN,U Mumba,1
385,NaN,0.33,NaN,NaN,3,239,Jishnu,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Telugu Titans,1
386,NaN,0.33,NaN,NaN,3,2351,Vikram Kandola,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Haryana Steelers,1
387,NaN,NaN,NaN,NaN,2,2025,Ajinkya Rohidas Kapre,1.0,1.0,NaN,NaN,NaN,NaN,NaN,U Mumba,1
388,NaN,NaN,NaN,NaN,3,774,Munish,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Telugu Titans,1
389,NaN,0.33,NaN,NaN,3,2671,Naveen Narwal,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Bengal Warriors,1
390,NaN,NaN,NaN,NaN,2,2668,Sumit,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Dabang Delhi K.C.,1
391,NaN,NaN,NaN,NaN,1,2515,Vikas Chhillar,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Haryana Steelers,1
392,NaN,NaN,NaN,NaN,1,2489,Satywan,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Dabang Delhi K.C.,1
393,NaN,NaN,NaN,NaN,3,2482,Aashish Nagar,NaN,NaN,1.0,NaN,NaN,NaN,1.0,U.P. Yoddha,1
394,NaN,NaN,NaN,NaN,2,2501,Aman,NaN,NaN,1.0,NaN,NaN,NaN,1.0,Bengaluru Bulls,1